name: CI/CD

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Flask app (smoke test)
        run: |
          python app.py &
          sleep 5 # Aguardar o servidor Flask iniciar
          curl --silent --fail http://127.0.0.1:8000 || exit 1
          kill $(jobs -p) # Finalizar o servidor Flask

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (simulado)
        run: echo "Deploy simulado - sucesso"
