name: CI/CD

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Smoke test
        run: echo "Sem testes automáticos ainda - build ok"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (simulado)
        run: echo "Deploy simulado - sucesso"
