name: CI/CD

on:
  push:
    branches: 
      - dev
      - main
  pull_request:
    branches: 
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Setup do Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Teste básico do Flask
      - name: Smoke test Flask
        run: |
          python app.py &  # Inicia o app Flask em background
          sleep 5  # Aguarda 5 segundos para garantir que o app iniciou
          curl --silent --fail http://127.0.0.1:8000 || exit 1  # Verifica se o serviço está ativo
          kill $(jobs -p)  # Para o Flask depois do teste

  # Fluxo de Deploy (Somente para branch 'main')
  deploy:
    needs: build  # O deploy depende do sucesso do job de build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Garante que o deploy só ocorra para a branch main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy (simulado)
        run: echo "Deploy simulado - sucesso"