name: CI/CD

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test Flask
        run: |
          python app.py &
          sleep 5
          curl --silent --fail http://127.0.0.1:8000 || exit 1
          kill $(jobs -p)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (simulado)
        run: echo "Deploy simulado - sucesso"
